//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 01:30:43 AM CEST 
//


package it.redhat.fsw.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.redhat.fsw.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Line_QNAME = new QName("urn:fsw-poc-service:1.0", "line");
    private final static QName _Total_QNAME = new QName("urn:fsw-poc-service:1.0", "total");
    private final static QName _OrderResponse_QNAME = new QName("urn:fsw-poc-service:1.0", "orderResponse");
    private final static QName _Order_QNAME = new QName("urn:fsw-poc-service:1.0", "order");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.redhat.fsw.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderPrice }
     * 
     */
    public OrderPrice createOrderPrice() {
        return new OrderPrice();
    }

    /**
     * Create an instance of {@link OrderLine }
     * 
     */
    public OrderLine createOrderLine() {
        return new OrderLine();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link OrderTotal }
     * 
     */
    public OrderTotal createOrderTotal() {
        return new OrderTotal();
    }

    /**
     * Create an instance of {@link OrderResponse }
     * 
     */
    public OrderResponse createOrderResponse() {
        return new OrderResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fsw-poc-service:1.0", name = "line")
    public JAXBElement<OrderLine> createLine(OrderLine value) {
        return new JAXBElement<OrderLine>(_Line_QNAME, OrderLine.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderTotal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fsw-poc-service:1.0", name = "total")
    public JAXBElement<OrderTotal> createTotal(OrderTotal value) {
        return new JAXBElement<OrderTotal>(_Total_QNAME, OrderTotal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fsw-poc-service:1.0", name = "orderResponse")
    public JAXBElement<OrderResponse> createOrderResponse(OrderResponse value) {
        return new JAXBElement<OrderResponse>(_OrderResponse_QNAME, OrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Order }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fsw-poc-service:1.0", name = "order")
    public JAXBElement<Order> createOrder(Order value) {
        return new JAXBElement<Order>(_Order_QNAME, Order.class, null, value);
    }

}
