//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.13 at 10:19:45 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:fsw-poc-service:1.0")
package it.redhat.fsw.domain;
